sudo: required
language: c
services:
  - docker
before_install:
  - docker pull bitcraze/builder
script:
  # Build basic config
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build

  # Build with TDOA3 longer range option
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build "EXTRA_CFLAGS=-DLPS_LONGER_RANGE"
